name: Process Configs

on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours
  workflow_dispatch: # Allow manual triggering

jobs:
  process-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests aiohttp

      - name: Run config processor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          python config_processor.py

      - name: Log run info
        run: |
          echo "Config processing completed at $(date)"
