name: Run Config Sender

on:
  schedule:
    - cron: "0 */4 * * *"  # Run every 12 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Limit execution time to 5 minutes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests aiohttp python-telegram-bot

    - name: Run script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: python v2ray_config_extractor.py
